# Generated by Django 5.0.1 on 2024-01-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='path',
        ),
    ]
